---
title: "Varroa cage trialsr"
author: "Reed Johnson"
date: "9/27/2022"
output: html_document
---

## Install libraries
```{r setup, include=FALSE, cache = FALSE}
require("knitr")
knitr::opts_chunk$set(echo = TRUE)
library(lubridate) # Deal with dates
library(plyr) #summarize by dates
library(dplyr) # remove duplicates
library(ggplot2) # plotting
library(googlesheets4) ## Read from GoogleDocs https://googlesheets4.tidyverse.org/
```

## Download GoogleSheet with data
```{r sheet_download}
gs4_deauth() ## Prevents google authorization; Needed for remote session (but keys must be used and sheets must be shared to anyone)
## Download data from all worksheets in google doc sheet
googleSheetsKey <- "1AzRyUUbEpHJjfKzXyccBazxftDhepGJGj31zzdPzrK4" #https://docs.google.com/spreadsheets/d/1AzRyUUbEpHJjfKzXyccBazxftDhepGJGj31zzdPzrK4/edit#gid=0
varroa_ss <- gs4_get(googleSheetsKey)
cage <- as.data.frame(read_sheet(googleSheetsKey, sheet = "Summary"))
write.csv(cage, file=paste("cage.csv", sep="_"))
```
### Load and prepare previously downloaded data
```{r load_file}
cage <- read.csv("cage.csv") ## Load csv file
cage <- cage[is.na(cage$flag),] ## Remove flagged lines
```

## Generate fenpyroximate summary
```{r fenpyroximate}
pdf(file="fenpyroximate_cage_tests.pdf")
fen <- subset(cage, active=="fenpyroximate")

## Mites
plot(fen$prop.mites.24 ~ as.factor(fen$pfa), las=2, ylab="proportion mites killed (24 h.)", xlab="principal functioning agent", main="Fenpyroximate (0.1% in glycerol)")
fen.mite.glm <- glm(cbind(mite.24, mite.48+mite.72+mites.washed) ~ pfa,
           family=binomial(logit), data=fen)
summary(fen.mite.glm)
## Bees
plot((fen$bee.24/fen$total.bees.count) ~ as.factor(fen$pfa), las=2, ylab="proportion bees killed (24 h.)", xlab="principal functioning agent", main="Fenpyroximate (0.1% in glycerol)")
fen.bee.glm <- glm(cbind(bee.24, round(total.bees.count) - bee.24) ~ pfa,
           family=binomial(logit), data=fen)
summary(fen.bee.glm)

tapply(fen$prop.mites.24, fen$pfa, mean)
tapply(fen$bee.24/fen$total.bees.count, fen$pfa, mean)
dev.off()
```

## Generate clove oil summary
```{r clove_oil}
pdf(file="clove_oil_cage_tests.pdf")
clove <- subset(cage, active=="clove oil")

## Mites
plot(clove$prop.mites.24 ~ as.factor(clove$pfa), las=2, ylab="proportion mites killed (24 h.)", xlab="principal functioning agent", main="Clove oil (0.3% in glycerol)")
clove.mite.glm <- glm(cbind(mite.24, mite.48+mite.72+mites.washed) ~ pfa,
           family=binomial(logit), data=clove)
summary(clove.mite.glm)

## Bees
plot((clove$bee.24/clove$total.bees.count) ~ as.factor(clove$pfa), las=2, ylab="proportion bees killed (24 h.)", xlab="principal functioning agent", main="Clove oil (0.3% in glycerol)")
clove.bee.glm <- glm(cbind(bee.24, round(total.bees.count) - bee.24) ~ pfa,
           family=binomial(logit), data=clove)
summary(clove.bee.glm)

tapply(clove$prop.mites.24, clove$pfa, mean)
tapply(clove$bee.24/clove$total.bees.count, clove$pfa, mean)
dev.off()
```


